### ISSUE TITLE
Any interest for global version?

### ISSUE THREAD

**Issue by Anyrainel** [190nm/rein-kuro#1]
Hi! Thanks a lot for making this available. I'm really interested in peeking into the global version. I tried your excellent tool on global data (which has 301 folder where you had 201) and found that the key is incorrect. At least that's what your script suggests.

Would you be able to share some hints on the key? I'm not really familiar with unity stuff. Is there a method that I should look for in the so files?

I'm Ofty#7090 on dc if you could discuss with me privately. I'm very interested in contributing.

**Comment by 190nm** [comment]
Thanks for the interest!

Yes, the global/en release of the game had changed the cache encryption key for some reason, but seemingly everything else is the same. Somehow I ended up fixing it to support other localizations of the game _right as this issue was opened_ and only noticed it as I was readying the new release. Should be fixed now, with some better instructions included as well.
I'll contact you soon when I have the time to discuss what I know about the game's systems in full.
